# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  schedule:
    - cron: '0 12 * * 6'  # Every Saturday at 12

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
      - name: Build
        run: go build
      - name: Run
        run: ./f1-reminders
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          PHONE_NUMBERS: ${{ secrets.PHONE_NUMBERS }}
          MessagingServiceSid: ${{ secrets.MessagingServiceSid }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
      
      
